version: '3.8'
services:
  whatsapp:
    image: ratna22/newwhatsapp:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3
  instagram:
    image: ratna22/newinstagram:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3
  facebook:
    image: ratna22/newfacebook:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3


